(function(){var d=true,e=null,h=false;function i(a){return function(b){this[a]=b}}function j(a){return function(){return this[a]}}var k;
function l(a,b,c){this.extend(l,google.maps.OverlayView);this.b=a;this.a=[];this.m=[];this.Z=[53,56,66,78,90];this.i=[];this.z=h;c=c||{};this.f=c.gridSize||60;this.U=c.maxZoom||e;this.i=c.styles||[];this.T=c.imagePath||this.N;this.S=c.imageExtension||this.M;this.L=d;if(c.zoomOnClick!=undefined)this.L=c.zoomOnClick;this.p=h;if(c.averageCenter!=undefined)this.p=c.averageCenter;m(this);this.setMap(a);this.H=this.b.getZoom();var f=this;google.maps.event.addListener(this.b,"zoom_changed",function(){var g=
f.b.mapTypes[f.b.getMapTypeId()].maxZoom,o=f.b.getZoom();if(!(o<0||o>g))if(f.H!=o){f.H=f.b.getZoom();f.k()}});google.maps.event.addListener(this.b,"idle",function(){f.h()});b&&b.length&&this.B(b,h)}k=l.prototype;k.N="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m";k.M="png";k.extend=function(a,b){return function(c){for(var f in c.prototype)this.prototype[f]=c.prototype[f];return this}.apply(a,[b])};k.onAdd=function(){if(!this.z){this.z=d;p(this)}};k.draw=function(){};
function m(a){if(!a.i.length)for(var b=0,c;c=a.Z[b];b++)a.i.push({url:a.T+(b+1)+"."+a.S,height:c,width:c})}k.w=j("i");k.v=j("a");k.R=function(){return this.a.length};k.G=function(){return this.U||this.b.mapTypes[this.b.getMapTypeId()].maxZoom};k.D=function(a,b){for(var c=0,f=a.length,g=f;g!==0;){g=parseInt(g/10,10);c++}c=Math.min(c,b);return{text:f,index:c}};k.X=i("D");k.F=j("D");k.B=function(a,b){for(var c=0,f;f=a[c];c++)q(this,f);b||this.h()};
function q(a,b){b.setVisible(h);b.setMap(e);b.r=h;b.draggable&&google.maps.event.addListener(b,"dragend",function(){b.r=h;a.k();a.h()});a.a.push(b)}k.o=function(a,b){q(this,a);b||this.h()};function r(a,b){var c=-1;if(a.a.indexOf)c=a.a.indexOf(b);else for(var f=0,g;g=a.a[f];f++)if(g==b){c=f;break}if(c==-1)return h;a.a.splice(c,1);b.setVisible(h);b.setMap(e);return d}k.V=function(a,b){var c=r(this,a);if(!b&&c){this.k();this.h();return d}else return h};
k.W=function(a,b){for(var c=h,f=0,g;g=a[f];f++)c=c||r(this,g);if(!b&&c){this.k();this.h();return d}};k.Q=function(){return this.m.length};k.getMap=j("b");k.setMap=i("b");k.u=j("f");k.Y=i("f");
function s(a,b){var c=a.getProjection(),f=new google.maps.LatLng(b.getNorthEast().lat(),b.getNorthEast().lng()),g=new google.maps.LatLng(b.getSouthWest().lat(),b.getSouthWest().lng());f=c.fromLatLngToDivPixel(f);f.x+=a.f;f.y-=a.f;g=c.fromLatLngToDivPixel(g);g.x-=a.f;g.y+=a.f;f=c.fromDivPixelToLatLng(f);c=c.fromDivPixelToLatLng(g);b.extend(f);b.extend(c);return b}k.O=function(){this.k();this.a=[]};
k.k=function(){for(var a=0,b;b=this.m[a];a++)b.remove();for(a=0;b=this.a[a];a++){b.r=h;b.setMap(e);b.setVisible(h)}this.m=[]};k.h=function(){p(this)};function p(a){if(a.z)for(var b=s(a,new google.maps.LatLngBounds(a.b.getBounds().getSouthWest(),a.b.getBounds().getNorthEast())),c=0,f;f=a.a[c];c++){var g=h;if(!f.r&&b.contains(f.getPosition())){for(var o=0,n;n=a.m[o];o++)if(!g&&n.getCenter()&&n.t.contains(f.getPosition())){g=d;n.o(f);break}if(!g){n=new t(a);n.o(f);a.m.push(n)}}}}
function t(a){this.j=a;this.b=a.getMap();this.f=a.u();this.p=a.p;this.d=e;this.a=[];this.t=e;this.l=new u(this,a.w(),a.u())}k=t.prototype;
k.o=function(a){var b;a:if(this.a.indexOf)b=this.a.indexOf(a)!=-1;else{b=0;for(var c;c=this.a[b];b++)if(c==a){b=d;break a}b=h}if(b)return h;if(this.d){if(this.p){b=(this.d.lat()+a.getPosition().lat())/2;c=(this.d.lng()+a.getPosition().lng())/2;this.d=new google.maps.LatLng(b,c);v(this)}}else{this.d=a.getPosition();v(this)}if(this.a.length==0){a.setMap(this.b);a.setVisible(d)}else if(this.a.length==1){this.a[0].setMap(e);this.a[0].setVisible(h)}a.r=d;this.a.push(a);if(this.b.getZoom()>this.j.G())for(a=
0;b=this.a[a];a++){b.setMap(this.b);b.setVisible(d)}else if(this.a.length<2)w(this.l);else{b=this.j.F()(this.a,this.j.w().length);this.l.setCenter(this.d);a=this.l;a.A=b;a.ba=b.text;a.$=b.index;if(a.c)a.c.innerHTML=b.text;b=Math.max(0,a.A.index-1);b=Math.min(a.i.length-1,b);b=a.i[b];a.K=b.url;a.g=b.height;a.n=b.width;a.I=b.textColor;a.e=b.anchor;a.J=b.textSize;a.C=b.backgroundPosition;this.l.show()}return d};k.getBounds=function(){v(this);return this.t};
k.remove=function(){this.l.remove();this.a.length=0;delete this.a};k.P=function(){return this.a.length};k.v=j("a");k.getCenter=j("d");function v(a){a.t=s(a.j,new google.maps.LatLngBounds(a.d,a.d))}k.getMap=j("b");function u(a,b,c){a.j.extend(u,google.maps.OverlayView);this.i=b;this.aa=c||0;this.q=a;this.d=e;this.b=a.getMap();this.A=this.c=e;this.s=h;this.setMap(this.b)}k=u.prototype;
k.onAdd=function(){this.c=document.createElement("DIV");if(this.s){this.c.style.cssText=x(this,y(this,this.d));this.c.innerHTML=this.A.text}this.getPanes().overlayImage.appendChild(this.c);var a=this;google.maps.event.addDomListener(this.c,"click",function(){var b=a.q.j;google.maps.event.trigger(b,"clusterclick",a.q);if(b.L){a.b.panTo(a.q.getCenter());a.b.fitBounds(a.q.getBounds())}})};
function y(a,b){var c=a.getProjection().fromLatLngToDivPixel(b);c.x-=parseInt(a.n/2,10);c.y-=parseInt(a.g/2,10);return c}k.draw=function(){if(this.s){var a=y(this,this.d);this.c.style.top=a.y+"px";this.c.style.left=a.x+"px"}};function w(a){if(a.c)a.c.style.display="none";a.s=h}k.show=function(){if(this.c){this.c.style.cssText=x(this,y(this,this.d));this.c.style.display=""}this.s=d};k.remove=function(){this.setMap(e)};
k.onRemove=function(){if(this.c&&this.c.parentNode){w(this);this.c.parentNode.removeChild(this.c);this.c=e}};k.setCenter=i("d");
function x(a,b){var c=[];if(document.all)c.push('filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src="'+a.K+'");');else{c.push("background-image:url("+a.K+");");c.push("background-position:"+(a.C?a.C:"0 0")+";")}if(typeof a.e==="object"){typeof a.e[0]==="number"&&a.e[0]>0&&a.e[0]<a.g?c.push("height:"+(a.g-a.e[0])+"px; padding-top:"+a.e[0]+"px;"):c.push("height:"+a.g+"px; line-height:"+a.g+"px;");typeof a.e[1]==="number"&&a.e[1]>0&&a.e[1]<a.n?c.push("width:"+(a.n-a.e[1])+
"px; padding-left:"+a.e[1]+"px;"):c.push("width:"+a.n+"px; text-align:center;")}else c.push("height:"+a.g+"px; line-height:"+a.g+"px; width:"+a.n+"px; text-align:center;");c.push("cursor:pointer; top:"+b.y+"px; left:"+b.x+"px; color:"+(a.I?a.I:"black")+"; position:absolute; font-size:"+(a.J?a.J:11)+"px; font-family:Arial,sans-serif; font-weight:bold");return c.join("")}window.MarkerClusterer=l;l.prototype.addMarker=l.prototype.o;l.prototype.addMarkers=l.prototype.B;l.prototype.clearMarkers=l.prototype.O;
l.prototype.getCalculator=l.prototype.F;l.prototype.getGridSize=l.prototype.u;l.prototype.getMap=l.prototype.getMap;l.prototype.getMarkers=l.prototype.v;l.prototype.getMaxZoom=l.prototype.G;l.prototype.getStyles=l.prototype.w;l.prototype.getTotalClusters=l.prototype.Q;l.prototype.getTotalMarkers=l.prototype.R;l.prototype.redraw=l.prototype.h;l.prototype.removeMarker=l.prototype.V;l.prototype.removeMarkers=l.prototype.W;l.prototype.resetViewport=l.prototype.k;l.prototype.setCalculator=l.prototype.X;
l.prototype.setGridSize=l.prototype.Y;l.prototype.onAdd=l.prototype.onAdd;l.prototype.draw=l.prototype.draw;t.prototype.getCenter=t.prototype.getCenter;t.prototype.getSize=t.prototype.P;t.prototype.getMarkers=t.prototype.v;u.prototype.onAdd=u.prototype.onAdd;u.prototype.draw=u.prototype.draw;u.prototype.onRemove=u.prototype.onRemove;
})();
