(function(){var d=true,f=null,i=false;function j(a){return function(b){this[a]=b}}function k(a){return function(){return this[a]}}var l;
function m(a,b,c){this.extend(m,google.maps.OverlayView);this.b=a;this.a=[];this.f=[];this.ba=[53,56,66,78,90];this.j=[];this.z=i;c=c||{};this.g=c.gridSize||60;this.X=c.maxZoom||f;this.j=c.styles||[];this.W=c.imagePath||this.P;this.V=c.imageExtension||this.O;this.N=d;if(c.zoomOnClick!=undefined)this.N=c.zoomOnClick;this.q=i;if(c.averageCenter!=undefined)this.q=c.averageCenter;n(this);this.setMap(a);this.I=this.b.getZoom();var e=this;google.maps.event.addListener(this.b,"zoom_changed",function(){var g=
e.b.mapTypes[e.b.getMapTypeId()].maxZoom,o=e.b.getZoom();if(!(o<0||o>g))if(e.I!=o){e.I=e.b.getZoom();e.l()}});google.maps.event.addListener(this.b,"idle",function(){e.i()});b&&b.length&&this.B(b,i)}l=m.prototype;l.P="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m";l.O="png";l.extend=function(a,b){return function(c){for(var e in c.prototype)this.prototype[e]=c.prototype[e];return this}.apply(a,[b])};l.onAdd=function(){if(!this.z){this.z=d;q(this)}};l.draw=function(){};
function n(a){if(!a.j.length)for(var b=0,c;c=a.ba[b];b++)a.j.push({url:a.W+(b+1)+"."+a.V,height:c,width:c})}l.R=function(){for(var a=this.n(),b=new google.maps.LatLngBounds,c=0,e;e=a[c];c++)b.extend(e.getPosition());this.b.fitBounds(b)};l.w=k("j");l.n=k("a");l.U=function(){return this.a.length};l.H=function(){return this.X||this.b.mapTypes[this.b.getMapTypeId()].maxZoom};l.F=function(a,b){for(var c=0,e=a.length,g=e;g!==0;){g=parseInt(g/10,10);c++}c=Math.min(c,b);return{text:e,index:c}};l.$=j("F");
l.G=k("F");l.B=function(a,b){for(var c=0,e;e=a[c];c++)t(this,e);b||this.i()};function t(a,b){b.r=i;b.draggable&&google.maps.event.addListener(b,"dragend",function(){b.r=i;a.J()});a.a.push(b)}l.p=function(a,b){t(this,a);b||this.i()};function u(a,b){var c=-1;if(a.a.indexOf)c=a.a.indexOf(b);else for(var e=0,g;g=a.a[e];e++)if(g==b){c=e;break}if(c==-1)return i;a.a.splice(c,1);return d}l.Y=function(a,b){var c=u(this,a);if(!b&&c){this.l();this.i();return d}else return i};
l.Z=function(a,b){for(var c=i,e=0,g;g=a[e];e++){g=u(this,g);c=c||g}if(!b&&c){this.l();this.i();return d}};l.T=function(){return this.f.length};l.getMap=k("b");l.setMap=j("b");l.v=k("g");l.aa=j("g");
l.u=function(a){var b=this.getProjection(),c=new google.maps.LatLng(a.getNorthEast().lat(),a.getNorthEast().lng()),e=new google.maps.LatLng(a.getSouthWest().lat(),a.getSouthWest().lng());c=b.fromLatLngToDivPixel(c);c.x+=this.g;c.y-=this.g;e=b.fromLatLngToDivPixel(e);e.x-=this.g;e.y+=this.g;c=b.fromDivPixelToLatLng(c);b=b.fromDivPixelToLatLng(e);a.extend(c);a.extend(b);return a};l.Q=function(){this.l(d);this.a=[]};
l.l=function(a){for(var b=0,c;c=this.f[b];b++)c.remove();for(b=0;c=this.a[b];b++){c.r=i;a&&c.setMap(f)}this.f=[]};l.J=function(){var a=this.f.slice();this.f.length=0;this.l();this.i();window.setTimeout(function(){for(var b=0,c;c=a[b];b++)c.remove()},0)};l.i=function(){q(this)};
function q(a){if(a.z)for(var b=a.u(new google.maps.LatLngBounds(a.b.getBounds().getSouthWest(),a.b.getBounds().getNorthEast())),c=0,e;e=a.a[c];c++)if(!e.r&&b.contains(e.getPosition())){var g=a;e=e;for(var o=4E4,r=f,x=0,p=void 0;p=g.f[x];x++){var h=p.getCenter();if(h){h=h;var s=e.getPosition();if(!h||!s)h=0;else{var y=(s.lat()-h.lat())*Math.PI/180,z=(s.lng()-h.lng())*Math.PI/180;h=Math.sin(y/2)*Math.sin(y/2)+Math.cos(h.lat()*Math.PI/180)*Math.cos(s.lat()*Math.PI/180)*Math.sin(z/2)*Math.sin(z/2);h=
6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}if(h<o){o=h;r=p}}}if(r&&r.D.contains(e.getPosition()))r.p(e);else{p=new v(g);p.p(e);g.f.push(p)}}}function v(a){this.k=a;this.b=a.getMap();this.g=a.v();this.q=a.q;this.d=f;this.a=[];this.D=f;this.m=new w(this,a.w(),a.v())}l=v.prototype;
l.p=function(a){var b;a:if(this.a.indexOf)b=this.a.indexOf(a)!=-1;else{b=0;for(var c;c=this.a[b];b++)if(c==a){b=d;break a}b=i}if(b)return i;if(this.d){if(this.q){c=this.a.length+1;b=(this.d.lat()*(c-1)+a.getPosition().lat())/c;c=(this.d.lng()*(c-1)+a.getPosition().lng())/c;this.d=new google.maps.LatLng(b,c);A(this)}}else{this.d=a.getPosition();A(this)}this.a.length==0&&a.getMap()!=this.b&&a.setMap(this.b);if(this.a.length>0){this.a.length==1&&this.a[0].setMap(f);a.setMap(f)}a.r=d;this.a.push(a);if(this.b.getZoom()>
this.k.H())for(a=0;b=this.a[a];a++)b.setMap(this.b);else if(this.a.length<2)B(this.m);else{b=this.k.G()(this.a,this.k.w().length);this.m.setCenter(this.d);a=this.m;a.A=b;a.ea=b.text;a.ca=b.index;if(a.c)a.c.innerHTML=b.text;b=Math.max(0,a.A.index-1);b=Math.min(a.j.length-1,b);b=a.j[b];a.M=b.url;a.h=b.height;a.o=b.width;a.K=b.textColor;a.e=b.anchor;a.L=b.textSize;a.C=b.backgroundPosition;this.m.show()}return d};
l.getBounds=function(){for(var a=new google.maps.LatLngBounds(this.d,this.d),b=this.n(),c=0,e;e=b[c];c++)a.extend(e.getPosition());return a};l.remove=function(){this.m.remove();this.a.length=0;delete this.a};l.S=function(){return this.a.length};l.n=k("a");l.getCenter=k("d");function A(a){a.D=a.k.u(new google.maps.LatLngBounds(a.d,a.d))}l.getMap=k("b");
function w(a,b,c){a.k.extend(w,google.maps.OverlayView);this.j=b;this.da=c||0;this.t=a;this.d=f;this.b=a.getMap();this.A=this.c=f;this.s=i;this.setMap(this.b)}l=w.prototype;l.onAdd=function(){this.c=document.createElement("DIV");if(this.s){this.c.style.cssText=C(this,D(this,this.d));this.c.innerHTML=this.A.text}this.getPanes().overlayImage.appendChild(this.c);var a=this;google.maps.event.addDomListener(this.c,"click",function(){var b=a.t.k;google.maps.event.trigger(b,"clusterclick",a.t);b.N&&a.b.fitBounds(a.t.getBounds())})};
function D(a,b){var c=a.getProjection().fromLatLngToDivPixel(b);c.x-=parseInt(a.o/2,10);c.y-=parseInt(a.h/2,10);return c}l.draw=function(){if(this.s){var a=D(this,this.d);this.c.style.top=a.y+"px";this.c.style.left=a.x+"px"}};function B(a){if(a.c)a.c.style.display="none";a.s=i}l.show=function(){if(this.c){this.c.style.cssText=C(this,D(this,this.d));this.c.style.display=""}this.s=d};l.remove=function(){this.setMap(f)};
l.onRemove=function(){if(this.c&&this.c.parentNode){B(this);this.c.parentNode.removeChild(this.c);this.c=f}};l.setCenter=j("d");
function C(a,b){var c=[];if(document.all)c.push('filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src="'+a.M+'");');else{c.push("background-image:url("+a.M+");");c.push("background-position:"+(a.C?a.C:"0 0")+";")}if(typeof a.e==="object"){typeof a.e[0]==="number"&&a.e[0]>0&&a.e[0]<a.h?c.push("height:"+(a.h-a.e[0])+"px; padding-top:"+a.e[0]+"px;"):c.push("height:"+a.h+"px; line-height:"+a.h+"px;");typeof a.e[1]==="number"&&a.e[1]>0&&a.e[1]<a.o?c.push("width:"+(a.o-a.e[1])+
"px; padding-left:"+a.e[1]+"px;"):c.push("width:"+a.o+"px; text-align:center;")}else c.push("height:"+a.h+"px; line-height:"+a.h+"px; width:"+a.o+"px; text-align:center;");c.push("cursor:pointer; top:"+b.y+"px; left:"+b.x+"px; color:"+(a.K?a.K:"black")+"; position:absolute; font-size:"+(a.L?a.L:11)+"px; font-family:Arial,sans-serif; font-weight:bold");return c.join("")}window.MarkerClusterer=m;m.prototype.addMarker=m.prototype.p;m.prototype.addMarkers=m.prototype.B;m.prototype.clearMarkers=m.prototype.Q;
m.prototype.fitMapToMarkers=m.prototype.R;m.prototype.getCalculator=m.prototype.G;m.prototype.getGridSize=m.prototype.v;m.prototype.getExtendedBounds=m.prototype.u;m.prototype.getMap=m.prototype.getMap;m.prototype.getMarkers=m.prototype.n;m.prototype.getMaxZoom=m.prototype.H;m.prototype.getStyles=m.prototype.w;m.prototype.getTotalClusters=m.prototype.T;m.prototype.getTotalMarkers=m.prototype.U;m.prototype.redraw=m.prototype.i;m.prototype.removeMarker=m.prototype.Y;m.prototype.removeMarkers=m.prototype.Z;
m.prototype.resetViewport=m.prototype.l;m.prototype.repaint=m.prototype.J;m.prototype.setCalculator=m.prototype.$;m.prototype.setGridSize=m.prototype.aa;m.prototype.onAdd=m.prototype.onAdd;m.prototype.draw=m.prototype.draw;v.prototype.getCenter=v.prototype.getCenter;v.prototype.getSize=v.prototype.S;v.prototype.getMarkers=v.prototype.n;w.prototype.onAdd=w.prototype.onAdd;w.prototype.draw=w.prototype.draw;w.prototype.onRemove=w.prototype.onRemove;
})();
