(function(){var d=true,e=null,g=false;function j(a){return function(b){this[a]=b}}function k(a){return function(){return this[a]}}var l;
function m(a,b,c){this.extend(m,google.maps.OverlayView);this.b=a;this.a=[];this.m=[];this.$=[53,56,66,78,90];this.i=[];this.A=g;c=c||{};this.f=c.gridSize||60;this.V=c.maxZoom||e;this.i=c.styles||[];this.U=c.imagePath||this.O;this.T=c.imageExtension||this.N;this.M=d;if(c.zoomOnClick!=undefined)this.M=c.zoomOnClick;this.p=g;if(c.averageCenter!=undefined)this.p=c.averageCenter;n(this);this.setMap(a);this.I=this.b.getZoom();var f=this;google.maps.event.addListener(this.b,"zoom_changed",function(){var h=
f.b.mapTypes[f.b.getMapTypeId()].maxZoom,o=f.b.getZoom();if(!(o<0||o>h))if(f.I!=o){f.I=f.b.getZoom();f.k()}});google.maps.event.addListener(this.b,"idle",function(){f.h()});b&&b.length&&this.C(b,g)}l=m.prototype;l.O="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m";l.N="png";l.extend=function(a,b){return function(c){for(var f in c.prototype)this.prototype[f]=c.prototype[f];return this}.apply(a,[b])};l.onAdd=function(){if(!this.A){this.A=d;q(this)}};l.draw=function(){};
function n(a){if(!a.i.length)for(var b=0,c;c=a.$[b];b++)a.i.push({url:a.U+(b+1)+"."+a.T,height:c,width:c})}l.z=k("i");l.w=k("a");l.S=function(){return this.a.length};l.H=function(){return this.V||this.b.mapTypes[this.b.getMapTypeId()].maxZoom};l.F=function(a,b){for(var c=0,f=a.length,h=f;h!==0;){h=parseInt(h/10,10);c++}c=Math.min(c,b);return{text:f,index:c}};l.Y=j("F");l.G=k("F");l.C=function(a,b){for(var c=0,f;f=a[c];c++)t(this,f);b||this.h()};
function t(a,b){b.setVisible(g);b.setMap(e);b.r=g;b.draggable&&google.maps.event.addListener(b,"dragend",function(){b.r=g;a.k();a.h()});a.a.push(b)}l.o=function(a,b){t(this,a);b||this.h()};function u(a,b){var c=-1;if(a.a.indexOf)c=a.a.indexOf(b);else for(var f=0,h;h=a.a[f];f++)if(h==b){c=f;break}if(c==-1)return g;a.a.splice(c,1);b.setVisible(g);b.setMap(e);return d}l.W=function(a,b){var c=u(this,a);if(!b&&c){this.k();this.h();return d}else return g};
l.X=function(a,b){for(var c=g,f=0,h;h=a[f];f++){h=u(this,h);c=c||h}if(!b&&c){this.k();this.h();return d}};l.R=function(){return this.m.length};l.getMap=k("b");l.setMap=j("b");l.v=k("f");l.Z=j("f");
l.u=function(a){var b=this.getProjection(),c=new google.maps.LatLng(a.getNorthEast().lat(),a.getNorthEast().lng()),f=new google.maps.LatLng(a.getSouthWest().lat(),a.getSouthWest().lng());c=b.fromLatLngToDivPixel(c);c.x+=this.f;c.y-=this.f;f=b.fromLatLngToDivPixel(f);f.x-=this.f;f.y+=this.f;c=b.fromDivPixelToLatLng(c);b=b.fromDivPixelToLatLng(f);a.extend(c);a.extend(b);return a};l.P=function(){this.k();this.a=[]};
l.k=function(){for(var a=0,b;b=this.m[a];a++)b.remove();for(a=0;b=this.a[a];a++){b.r=g;b.setMap(e);b.setVisible(g)}this.m=[]};l.h=function(){q(this)};
function q(a){if(a.A)for(var b=a.u(new google.maps.LatLngBounds(a.b.getBounds().getSouthWest(),a.b.getBounds().getNorthEast())),c=0,f;f=a.a[c];c++)if(!f.r&&b.contains(f.getPosition())){var h=a;f=f;for(var o=4E4,r=e,y=0,p=void 0;p=h.m[y];y++){var i=p.getCenter();if(i){i=i;var s=f.getPosition();if(!i||!s)i=0;else{var z=(s.lat()-i.lat())*Math.PI/180,A=(s.lng()-i.lng())*Math.PI/180;i=Math.sin(z/2)*Math.sin(z/2)+Math.cos(i.lat()*Math.PI/180)*Math.cos(s.lat()*Math.PI/180)*Math.sin(A/2)*Math.sin(A/2);i=
6371*2*Math.atan2(Math.sqrt(i),Math.sqrt(1-i))}if(i<o){o=i;r=p}}}if(r&&r.t.contains(f.getPosition()))r.o(f);else{p=new v(h);p.o(f);h.m.push(p)}}}function v(a){this.j=a;this.b=a.getMap();this.f=a.v();this.p=a.p;this.d=e;this.a=[];this.t=e;this.l=new w(this,a.z(),a.v())}l=v.prototype;
l.o=function(a){var b;a:if(this.a.indexOf)b=this.a.indexOf(a)!=-1;else{b=0;for(var c;c=this.a[b];b++)if(c==a){b=d;break a}b=g}if(b)return g;if(this.d){if(this.p){c=this.a.length+1;b=(this.d.lat()*(c-1)+a.getPosition().lat())/c;c=(this.d.lng()*(c-1)+a.getPosition().lng())/c;this.d=new google.maps.LatLng(b,c);x(this)}}else{this.d=a.getPosition();x(this)}if(this.a.length==0){a.setMap(this.b);a.setVisible(d)}else if(this.a.length==1){this.a[0].setMap(e);this.a[0].setVisible(g)}a.r=d;this.a.push(a);if(this.b.getZoom()>
this.j.H())for(a=0;b=this.a[a];a++){b.setMap(this.b);b.setVisible(d)}else if(this.a.length<2)B(this.l);else{b=this.j.G()(this.a,this.j.z().length);this.l.setCenter(this.d);a=this.l;a.B=b;a.ca=b.text;a.aa=b.index;if(a.c)a.c.innerHTML=b.text;b=Math.max(0,a.B.index-1);b=Math.min(a.i.length-1,b);b=a.i[b];a.L=b.url;a.g=b.height;a.n=b.width;a.J=b.textColor;a.e=b.anchor;a.K=b.textSize;a.D=b.backgroundPosition;this.l.show()}return d};l.getBounds=function(){x(this);return this.t};
l.remove=function(){this.l.remove();this.a.length=0;delete this.a};l.Q=function(){return this.a.length};l.w=k("a");l.getCenter=k("d");function x(a){a.t=a.j.u(new google.maps.LatLngBounds(a.d,a.d))}l.getMap=k("b");function w(a,b,c){a.j.extend(w,google.maps.OverlayView);this.i=b;this.ba=c||0;this.q=a;this.d=e;this.b=a.getMap();this.B=this.c=e;this.s=g;this.setMap(this.b)}l=w.prototype;
l.onAdd=function(){this.c=document.createElement("DIV");if(this.s){this.c.style.cssText=C(this,D(this,this.d));this.c.innerHTML=this.B.text}this.getPanes().overlayImage.appendChild(this.c);var a=this;google.maps.event.addDomListener(this.c,"click",function(){var b=a.q.j;google.maps.event.trigger(b,"clusterclick",a.q);if(b.M){a.b.panTo(a.q.getCenter());a.b.fitBounds(a.q.getBounds())}})};
function D(a,b){var c=a.getProjection().fromLatLngToDivPixel(b);c.x-=parseInt(a.n/2,10);c.y-=parseInt(a.g/2,10);return c}l.draw=function(){if(this.s){var a=D(this,this.d);this.c.style.top=a.y+"px";this.c.style.left=a.x+"px"}};function B(a){if(a.c)a.c.style.display="none";a.s=g}l.show=function(){if(this.c){this.c.style.cssText=C(this,D(this,this.d));this.c.style.display=""}this.s=d};l.remove=function(){this.setMap(e)};
l.onRemove=function(){if(this.c&&this.c.parentNode){B(this);this.c.parentNode.removeChild(this.c);this.c=e}};l.setCenter=j("d");
function C(a,b){var c=[];if(document.all)c.push('filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src="'+a.L+'");');else{c.push("background-image:url("+a.L+");");c.push("background-position:"+(a.D?a.D:"0 0")+";")}if(typeof a.e==="object"){typeof a.e[0]==="number"&&a.e[0]>0&&a.e[0]<a.g?c.push("height:"+(a.g-a.e[0])+"px; padding-top:"+a.e[0]+"px;"):c.push("height:"+a.g+"px; line-height:"+a.g+"px;");typeof a.e[1]==="number"&&a.e[1]>0&&a.e[1]<a.n?c.push("width:"+(a.n-a.e[1])+
"px; padding-left:"+a.e[1]+"px;"):c.push("width:"+a.n+"px; text-align:center;")}else c.push("height:"+a.g+"px; line-height:"+a.g+"px; width:"+a.n+"px; text-align:center;");c.push("cursor:pointer; top:"+b.y+"px; left:"+b.x+"px; color:"+(a.J?a.J:"black")+"; position:absolute; font-size:"+(a.K?a.K:11)+"px; font-family:Arial,sans-serif; font-weight:bold");return c.join("")}window.MarkerClusterer=m;m.prototype.addMarker=m.prototype.o;m.prototype.addMarkers=m.prototype.C;m.prototype.clearMarkers=m.prototype.P;
m.prototype.getCalculator=m.prototype.G;m.prototype.getGridSize=m.prototype.v;m.prototype.getExtendedBounds=m.prototype.u;m.prototype.getMap=m.prototype.getMap;m.prototype.getMarkers=m.prototype.w;m.prototype.getMaxZoom=m.prototype.H;m.prototype.getStyles=m.prototype.z;m.prototype.getTotalClusters=m.prototype.R;m.prototype.getTotalMarkers=m.prototype.S;m.prototype.redraw=m.prototype.h;m.prototype.removeMarker=m.prototype.W;m.prototype.removeMarkers=m.prototype.X;m.prototype.resetViewport=m.prototype.k;
m.prototype.setCalculator=m.prototype.Y;m.prototype.setGridSize=m.prototype.Z;m.prototype.onAdd=m.prototype.onAdd;m.prototype.draw=m.prototype.draw;v.prototype.getCenter=v.prototype.getCenter;v.prototype.getSize=v.prototype.Q;v.prototype.getMarkers=v.prototype.w;w.prototype.onAdd=w.prototype.onAdd;w.prototype.draw=w.prototype.draw;w.prototype.onRemove=w.prototype.onRemove;
})();
